name: "Feature request"
description: "Request feature to be added, new command or other addition."
title: "[Feature]: "
labels: ["enhancement"]

body:
  - type: 'markdown'
    attributes:
      value: |
        Thank you for taking the time to fill out an issue. This template is meant for feature requests and improvements to already existing functionality.
  - type: 'input'
    attributes:
      label: 'What component of VOTL bot (docs, commands, ...) would you like to see improvements on?'
      placeholder: 'Command'
    validations:
      required: true
  - type: 'textarea'
    attributes:
      label: "Describe the enhancement you're suggesting."
      description: |
        Feel free to describe in as much detail as you wish.
    validations:
      required: true
  - type: 'textarea'
    attributes:
      label: 'Anything else?'
      description: 'Let us know if you have anything else to share.'